### PR TITLE
Feature: JsonSerializable implementation

### PR DESCRIPTION
**Pull request by alchm**
May be the use of the JsonSerializable interface could be more graceful ? :)
The tests are ok (except the one about __toString, that I changed)

### CODE REVIEW

**Comment by NanneHuiges** [comment]
Jamie has  moved the library over to me so I can maybe put some time in, so i'll be looking at this pull request. 
Code looks good, but am I correct that this pulls the required php version up to 5.4 where it wasn't before?

**Comment by NanneHuiges** [comment]
Unless I missed something in the serializabe, I suggest we don't remove the toString, as it might break applications that rely on it?

**Comment by alchm** [comment]
You are right, the JsonSerializable interface requires php version >= 5.4, so projects using an older php version must upgrade to use it. It is up to you to judge if upgrading the required php version is meaningful.
It is also right that removing the __toString method could break older applications. I suggest you put it back to maintain compatibility, but personally, I dislike php magic methods :)

**Comment by NanneHuiges** [comment]
I will do a new release with 5.4, with a 2.0 version, that will probably keep breakage to a minimum, but i'll re-add the magic method. While I do agree on your opinion, it is in there for now, and it doesn't bug me that much :)

might take a bit though, fixing some minor things first :)

**Comment by shkm** [comment]
I'd stay with `__toString`, but I'm a Rails guy these days, and therefore kind of used to magic ;-). Up to you, @NanneHuiges, but I also don't see that it hurts any.

**Comment by NanneHuiges** [comment]
I see no issue in having both ;)

**Pull request merged**
